{{- if not (lookup "v1" "secret" "{{ .Release.Namespace }}" "{{  .Release.Name }}-secret") -}} }}
apiVersion: v1
kind: Secret
metadata:
  name: {{  .Release.Name }}-secret
stringData:
  DBUSER: {{ .Values.global.db.user | default "NEWDBUSER" }}
  DBPASS: {{ .Values.global.db.pass | default "NEWDBPASS" }}
  DBNAME: {{ .Values.global.db.db | default "NEWDBNAME" }}
{{ end }}
