{{- if not (.Values.global.db.host) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
{{ end }}