{{- if not (lookup "v1" "secret" "{{ .Release.Namespace }}" "{{  .Release.Name }}-secret") -}}
apiVersion: v1
kind: ConfigMap
data:
  DBHOST: {{ .Release.Name }}-db
metadata:
  name: {{ .Release.Name }}-configmap
{{ end }}