{{- if not (lookup "v1" "secret" "{{ .Release.Namespace }}" "{{  .Release.Name }}-secret") -}}
apiVersion: v1
kind: ConfigMap
data:
  {{- if .Value.global.db.name }}
  DBHOST: "{{ .Values.global.db.host }}"
  {{- else }}
  DBHOST: "{{ .Values.db.name }}"
  {{ end }}
metadata:
  name: {{ include "web.fullname" . }}-configmap
{{ end }}