{{- if not (lookup "rbac.authorization.k8s.io/v1" "RoleBinding" .Release.Namespace "webapp-getpods") -}}
apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: webapp-getpods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webapp-getpods
subjects:
- kind: ServiceAccount
  name: "{{.Values.serviceAccount.name}}"
  namespace: {{.Release.Namespace}}
{{ end }}