{{- if not (lookup "rbac.authorization.k8s.io/v1" "ServiceAccount" "{{ .Release.Namespace }}" "webapp-getpods") -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-getpods
  labels:
    {{- include "web.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{ end }}
