# Default values for web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: docker.ask4ua.com/web
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  name: webapp-getpods

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: webapp.ask4ua.com
      #namespace is added 
      paths: ["","/"]

db: 
  name: webapp-db

envs:
- name: DBUSER
  key: DBUSER
- name: DBPASS
  key: DBPASS
- name: DBNAME
  key: DBNAME
