apiVersion: v1
kind: Secret
metadata:
  name: {{  .Release.Name }}-secret
stringData:
  DBUSER: {{ .Values.db.user | default "NEWDBUSER" }}
  DBPASS: {{ .Values.db.pass | default "NEWDBPASS" }}
  DBNAME: {{ .Values.db.db | default "NEWDBNAME" }}
